sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t davidstna/frontend .

script:
  - docker run davidstna/frontend npm run test -- --no-watchAll

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-771629859941"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY